# Laboratorio #3

In [1]:
import numpy as np
import pandas as pd

## Parte 1

### 1. ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [7]:
array_1 = np.full((1000, 1), True)

In [8]:
print(array_1.dtype)

bool


In [10]:
print("Array bytes: ", array_1.size*array_1.itemsize)

Array bytes:  1000


### 2. Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.


In [17]:
array_2 = np.arange(100,1,-1)
array_2 = array_2[array_2%2==0]
print(array_2[-10:])

[20 18 16 14 12 10  8  6  4  2]


### 3. Dado el array<br>
[2 4 5 6<br>
0 3 7 4<br>
8 8 5 2<br>
1 5 6 1]<br>

<br>
Seleccione con una instrucción el subarray de elementos [0 3 7 4]
<br>
Después, seleccione el subarray de elementos<br>
[
2 5<br>
8 5]

In [34]:
array_3 = np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])
array_3_1 = np.array([0,3,7,4])
array_3_2 = np.array([[2,5],[8,5]])

In [35]:
array_3[1]

array([0, 3, 7, 4])

In [69]:
array_3[[0,2], :][:, [0,2]] 

array([[2, 5],
       [8, 5]])

### 4. Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).

In [72]:
a = np.array([1,4,2,7])
b = np.array([1,3,2,9])

In [73]:
np.mean(a-b)

-0.25

### 5.